/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define CHATPROG ((rpc_uint)0x20000099)
#define CHATVERS ((rpc_uint)1)

#ifdef __cplusplus
#define WRITE ((rpc_uint)1)
extern "C" int * write_1(char **, CLIENT *);
extern "C" int * write_1_svc(char **, struct svc_req *);
#define GETCHAT ((rpc_uint)2)
extern "C" char ** getchat_1(int *, CLIENT *);
extern "C" char ** getchat_1_svc(int *, struct svc_req *);

#elif __STDC__
#define WRITE ((rpc_uint)1)
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
#define GETCHAT ((rpc_uint)2)
extern  char ** getchat_1(int *, CLIENT *);
extern  char ** getchat_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define WRITE ((rpc_uint)1)
extern  int * write_1();
extern  int * write_1_svc();
#define GETCHAT ((rpc_uint)2)
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
#endif /* Old Style C */

#endif /* !_CHAT_H_RPCGEN */
